format = """
$git_branch\
$git_status\
[](fg:#999999)\
$directory\
[](fg:#999999)\
$time\
$character\
"""
 
# Disable the blank line at the start of the prompt
add_newline = false

# TODO
# is_git_dir = "$(command git rev-parse --is-inside-work-tree 2> /dev/null)"
 
# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
 
[directory]
style = "fg:#367ab7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "🎜 "
"Pictures" = "📷 "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
 
[git_branch]
symbol = ""
style = "fg:#FCA17D"
# if [[ "$is_git_dir" == "true" ]]; then
format = '[ $symbol $branch ]($style)'
# when = '[ "$is_git_dir" == "true" ]'
 
[git_status]
style = "fg:#FCA17D"
# if [[ "$is_git_dir" == "true" ]]; then
# format = '[($all_status$ahead_behind )]($style)'
format = '[($all_status$ahead_behind)]($style)'
# when = '[ "$is_git_dir" == "true" ]'
 
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#33658A"
format = '[ $time ]($style)'

[character]
success_symbol = '[](fg:#33658A)'
